import { Prisma } from '@prisma/client';

export type QuestSeed = {
  slug: string;
  title: string;
  description: string;
  rewardKc: number;
  type: string;
  category: string;
  sortOrder: number;
  ctaLabel?: string;
  externalUrl?: string;
  icon?: string;
  verifyMode: string;
  meta?: Prisma.InputJsonValue;
  active: boolean;
  cooldownHours: number | null;
  maxClaimsPerUser: number;
};

function envUrl(key: string, fallback: string): string {
  return process.env[key]?.trim() || fallback;
}

export function buildMarketingQuestCatalog(): QuestSeed[] {
  return [
    {
      slug: 'onboarding-profile',
      title: 'Hoàn thiện hồ sơ',
      description:
        'Cập nhật username hoặc avatar — tăng uy tín khi chia sẻ KingCoin.',
      rewardKc: 500,
      type: 'onboarding',
      category: 'onboarding',
      sortOrder: 10,
      ctaLabel: 'Mở tài khoản',
      verifyMode: 'auto',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'first-trade',
      title: 'Đặt lệnh đầu tiên',
      description: 'Trải nghiệm khớp lệnh spot mô phỏng trên sàn.',
      rewardKc: 300,
      type: 'onboarding',
      category: 'onboarding',
      sortOrder: 20,
      ctaLabel: 'Giao dịch ngay',
      verifyMode: 'auto',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'add-watchlist-3',
      title: 'Theo dõi 3 token',
      description: 'Thêm 3 mã vào watchlist để bám sát thị trường.',
      rewardKc: 200,
      type: 'onboarding',
      category: 'onboarding',
      sortOrder: 30,
      ctaLabel: 'Khám phá thị trường',
      verifyMode: 'auto',
      meta: { minWatchlist: 3 },
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'convert-first',
      title: 'Chuyển đổi lần đầu',
      description: 'Swap KC ↔ altcoin trên cổng Convert.',
      rewardKc: 250,
      type: 'onboarding',
      category: 'onboarding',
      sortOrder: 40,
      ctaLabel: 'Mở Convert',
      verifyMode: 'auto',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'daily-login',
      title: 'Đăng nhập hôm nay',
      description: 'Quay lại mỗi ngày — không bỏ sót biến động thị trường.',
      rewardKc: 100,
      type: 'daily',
      category: 'daily',
      sortOrder: 50,
      ctaLabel: 'Nhận thưởng',
      verifyMode: 'auto',
      active: true,
      cooldownHours: 20,
      maxClaimsPerUser: 9999,
    },
    {
      slug: 'weekly-active-trader',
      title: 'Trader tích cực tuần',
      description: 'Đặt ít nhất 3 lệnh trong 7 ngày qua.',
      rewardKc: 350,
      type: 'daily',
      category: 'daily',
      sortOrder: 60,
      ctaLabel: 'Giao dịch',
      verifyMode: 'auto',
      meta: { minOrders7d: 3 },
      active: true,
      cooldownHours: 168,
      maxClaimsPerUser: 9999,
    },
    {
      slug: 'referral-first-friend',
      title: 'Mời bạn đầu tiên',
      description:
        'Bạn bè đăng ký qua link mời và đặt ít nhất một lệnh.',
      rewardKc: 400,
      type: 'growth',
      category: 'growth',
      sortOrder: 100,
      ctaLabel: 'Copy link mời',
      verifyMode: 'auto',
      meta: { minQualifiedReferrals: 1 },
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'referral-3-friends',
      title: 'Mời 3 bạn tham gia',
      description: 'Ba người được mời đã đăng ký và giao dịch.',
      rewardKc: 1200,
      type: 'growth',
      category: 'growth',
      sortOrder: 110,
      ctaLabel: 'Xem tiến độ',
      verifyMode: 'auto',
      meta: { minQualifiedReferrals: 3 },
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'referee-welcome',
      title: 'Chào mừng bạn được mời',
      description: 'Bạn đăng ký qua mã giới thiệu — thưởng chào mừng.',
      rewardKc: 200,
      type: 'growth',
      category: 'growth',
      sortOrder: 120,
      ctaLabel: 'Nhận KC',
      verifyMode: 'auto',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'share-referral-card',
      title: 'Chia sẻ mã mời',
      description: 'Copy link giới thiệu để lan tỏa KingCoin.',
      rewardKc: 100,
      type: 'growth',
      category: 'growth',
      sortOrder: 130,
      ctaLabel: 'Copy mã',
      verifyMode: 'auto',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'share-trade-link',
      title: 'Chia sẻ cặp giao dịch',
      description: 'Gửi link terminal trade cho bạn bè.',
      rewardKc: 150,
      type: 'social',
      category: 'social',
      sortOrder: 200,
      ctaLabel: 'Chia sẻ',
      verifyMode: 'delayed_honor',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'share-token-page',
      title: 'Chia sẻ trang token',
      description: 'Quảng bá một mã coin bạn quan tâm.',
      rewardKc: 150,
      type: 'social',
      category: 'social',
      sortOrder: 210,
      ctaLabel: 'Chia sẻ',
      verifyMode: 'delayed_honor',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'social-follow-facebook',
      title: 'Theo dõi Facebook',
      description: 'Tham gia cộng đồng KingCoin trên Facebook.',
      rewardKc: 100,
      type: 'social',
      category: 'social',
      sortOrder: 220,
      ctaLabel: 'Mở Facebook',
      externalUrl: envUrl(
        'QUEST_SOCIAL_FACEBOOK_URL',
        'https://www.facebook.com/',
      ),
      verifyMode: 'external_then_claim',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'social-follow-zalo',
      title: 'Theo dõi Zalo',
      description: 'Kết nối kênh Zalo chính thức.',
      rewardKc: 100,
      type: 'social',
      category: 'social',
      sortOrder: 230,
      ctaLabel: 'Mở Zalo',
      externalUrl: envUrl('QUEST_SOCIAL_ZALO_URL', 'https://zalo.me/'),
      verifyMode: 'external_then_claim',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'create-token',
      title: 'Phát hành token của bạn',
      description: 'Tạo coin riêng và niêm yết trên sàn mô phỏng.',
      rewardKc: 500,
      type: 'creator',
      category: 'creator',
      sortOrder: 300,
      ctaLabel: 'Tạo token',
      verifyMode: 'auto',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
    {
      slug: 'share-my-token',
      title: 'Quảng bá token của tôi',
      description: 'Chia sẻ trang token bạn đã phát hành.',
      rewardKc: 300,
      type: 'creator',
      category: 'creator',
      sortOrder: 310,
      ctaLabel: 'Chia sẻ',
      verifyMode: 'delayed_honor',
      active: true,
      cooldownHours: null,
      maxClaimsPerUser: 1,
    },
  ];
}
